services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1

  order-service:
    build: ./order-service
    volumes:
      - ./order-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./order-service/.env
    ports:
      - "3001:3000"
    depends_on:
      - localstack

  payment-service:
    build: ./payment-service
    volumes:
      - ./payment-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./payment-service/.env
    depends_on:
      - localstack
